version: '3.4'

services:
  lingvamvc:
    image: ${DOCKER_REGISTRY}lingvamvc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6002:6002"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"