// <auto-generated />
using System;
using Lingva.DAL.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lingva.DAL.EF.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    partial class DictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lingva.DAL.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("LanguageId");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(6867),
                            Date = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(6878),
                            Description = "Good movie",
                            LanguageId = 1,
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(6874),
                            Name = "Harry Potter",
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8180),
                            Date = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8192),
                            Description = "Eq",
                            LanguageId = 1,
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8189),
                            Name = "Librium",
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8206),
                            Date = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8210),
                            Description = "stuff",
                            LanguageId = 2,
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8208),
                            Name = "2Guns",
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.GroupUser", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("UserId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<int>("Id");

                    b.Property<DateTime?>("ModifyDate");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            UserId = 1,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(645),
                            Id = 1,
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(649)
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 2,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(1564),
                            Id = 2,
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(1572)
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 972, DateTimeKind.Local).AddTicks(8661),
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(3697),
                            Name = "en"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(5101),
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(5110),
                            Name = "ru"
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8880),
                            Email = "veloceraptor89@gmail.com",
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 977, DateTimeKind.Local).AddTicks(8885),
                            Name = "Serhii"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(324),
                            Email = "tucker_serega@mail.ru",
                            ModifyDate = new DateTime(2019, 6, 12, 13, 35, 20, 978, DateTimeKind.Local).AddTicks(333),
                            Name = "Old"
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.Group", b =>
                {
                    b.HasOne("Lingva.DAL.Entities.Language", "Language")
                        .WithMany("Groups")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lingva.DAL.Entities.GroupUser", b =>
                {
                    b.HasOne("Lingva.DAL.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lingva.DAL.Entities.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
